// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjB-KGiuUj0m_uQtyZViagRqIAqEUe0jg',
    appId: '1:535539685435:web:27b1352712de3468c5641e',
    messagingSenderId: '535539685435',
    projectId: 'cw06-bb432',
    authDomain: 'cw06-bb432.firebaseapp.com',
    storageBucket: 'cw06-bb432.firebasestorage.app',
    measurementId: 'G-XY33N6VF33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKT4Cz6n1HA0lrg_5ZrJYGewFuzSEQ7_4',
    appId: '1:535539685435:android:6ed1d3325a6ede95c5641e',
    messagingSenderId: '535539685435',
    projectId: 'cw06-bb432',
    storageBucket: 'cw06-bb432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvUmOseS0LKGXeLAyRd7vJMOtEg9-bsjE',
    appId: '1:535539685435:ios:bfe38d3043204046c5641e',
    messagingSenderId: '535539685435',
    projectId: 'cw06-bb432',
    storageBucket: 'cw06-bb432.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvUmOseS0LKGXeLAyRd7vJMOtEg9-bsjE',
    appId: '1:535539685435:ios:bfe38d3043204046c5641e',
    messagingSenderId: '535539685435',
    projectId: 'cw06-bb432',
    storageBucket: 'cw06-bb432.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjB-KGiuUj0m_uQtyZViagRqIAqEUe0jg',
    appId: '1:535539685435:web:a8b49542b45ee10ac5641e',
    messagingSenderId: '535539685435',
    projectId: 'cw06-bb432',
    authDomain: 'cw06-bb432.firebaseapp.com',
    storageBucket: 'cw06-bb432.firebasestorage.app',
    measurementId: 'G-1L0T954PP3',
  );
}
